---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployement
  labels:
    type: proxy
    author: srikrshna
spec:
  replicas: 3
  selector:
    matchLabels: 
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy 
    spec:
      containers: 
        - name: mynginxd
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090

