---
apiVersion: v1
kind: Pod
metadata: 
 name: postgress-pod
 labels: 
  type: db
  author: srikrishna
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: srikrishna
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb

...
