---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    author: srikrishna
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: webserver
