---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    author: srikrishna
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    author: srikrishna
    type: proxy
...

