---
apiVersion: v1
kind: Pod
metadata: 
  name: mytomcat-pod
  namespace: test-ns
  labels: 
   type: appserver
   author: srikrishna
spec:
 containers:
  - name: mytomcat
    image: tomee
    ports:
      - containerPort: 8080
        hostPort: 8080
